/// Sets of extension methods used by code generated by `SwiftCodeGen`.
extension StringStream {
    /// Returns `true` if the given consumer closure which takes as input a
    /// `StringStream` object and returns a `bool` value, when invoked with `self`
    /// at the current state, returns `false`.
    ///
    /// The state of `self` is restored to before this call on either results of
    /// `consumer`.
    @inlinable
    public mutating func negativeLookahead(_ consumer: (inout StringStream) throws -> Bool) rethrows -> Bool {
        let state = save()
        defer { restore(state) }

        return try !consumer(&self)
    }
}
